# coding: utf-8
# ========================================
# QMT Backtest Configuration
# ========================================

# ---------- Runtime Mode ----------
# quote_mode: 行情模式
#   - 'history': 只使用历史数据（回测）
#   - 'realtime': 只订阅实时行情（实盘/模拟盘）
#   - 'all': 历史+实时（先回测再实盘）
quote_mode: 'history'

# trade_mode: 交易模式
#   - 'backtest': 历史回测（虚拟交易）
#   - 'simulation': 模拟盘（仿真交易）
#   - 'trading': 实盘交易（真实资金）
trade_mode: 'backtest'

# title: 策略名称（显示在QMT界面，可选）
#   - 默认使用脚本文件名
title: ''

# ---------- Market Data ----------
# stock_code: 主股票代码（回测时间轴参考）
#   - 格式: '代码.市场'，如 '000001.SZ'（平安银行）
#   - 用于生成K线时间序列，决定 handlebar 调用时机
stock_code: '000001.SZ'

# period: K线周期（决定 handlebar 调用频率）
#   - 'tick': 逐笔成交
#   - '1m', '3m', '5m', '10m', '15m', '30m': 分钟线
#   - '1h': 小时线
#   - '1d': 日线
#   - '1w': 周线
#   - '1mon': 月线
#   - '1q': 季线
#   - '1hy': 半年线
#   - '1y': 年线
period: '1m'

# start_time: 回测开始时间
#   - 格式: 'YYYY-MM-DD' 或 'YYYY-MM-DD HH:MM:SS'
start_time: '2025-09-01'

# end_time: 回测结束时间
#   - 格式: 'YYYY-MM-DD' 或 'YYYY-MM-DD HH:MM:SS'
end_time: '2025-10-01'

# dividend_type: 除权方式
#   - 'none': 不复权（真实价格）
#   - 'front': 前复权（当前价格为准）
#   - 'back': 后复权（上市价格为准）
#   - 'front_ratio': 等比前复权
dividend_type: 'front_ratio'

# ---------- Backtest Parameters ----------
backtest:
  # asset: 初始资金（元）
  asset: 10000000.0

  # margin_ratio: 保证金比例（期货用，股票通常不用）
  #   - 0.05 表示 5% 保证金
  margin_ratio: 0.05

  # slippage_type: 滑点类型
  #   - 0: 无滑点
  #   - 1: 固定金额滑点（每笔固定损失）
  #   - 2: 比例滑点（按交易额比例）
  slippage_type: 2

  # slippage: 滑点值
  #   - slippage_type=2 时: 0.001 表示 0.1% 的价格偏离
  #   - 实际成交价 = 下单价 * (1 +/- slippage)
  #   - 买入时上浮，卖出时下降
  slippage: 0.001

  # max_vol_rate: 最大成交量占比
  #   - 单笔订单不能超过市场成交量的比例
  #   - 0.1 表示最多吃掉 10% 的市场成交量
  #   - 0 表示不限制
  max_vol_rate: 0.20

  # comsisson_type: 佣金类型
  #   - 0: 按金额比例
  #   - 1: 按固定金额
  comsisson_type: 0

  # open_tax: 开仓印花税率
  #   - A股买入无印花税，通常为 0.0
  open_tax: 0.0

  # close_tax: 平仓印花税率
  #   - A股卖出印花税 0.1%，即 0.001
  close_tax: 0.001

  # min_commission: 最小佣金（元）
  #   - 券商常见规则: 每笔最低 5 元
  min_commission: 5

  # open_commission: 开仓佣金率
  #   - 0.0003 表示万三
  #   - 实际佣金 = max(交易额 * open_commission, min_commission)
  open_commission: 0.0003

  # close_commission: 平仓佣金率
  #   - 0.0003 表示万三
  close_commission: 0.0003

  # close_today_commission: 平今佣金率（期货T+0用）
  #   - A股T+1，通常不用此参数
  close_today_commission: 0.0

  # benchmark: 业绩基准指数
  #   - 用于计算相对收益、alpha、beta
  #   - '000300.SH': 沪深300指数
  #   - '000905.SH': 中证500指数
  #   - '000001.SH': 上证指数
  benchmark: '000300.SH'

  # price_type: 下单价格类型
  #   - 11: 指定价（使用传入的price参数）
  #   - 5: 最新价（市价单）
  #   - 44: 对手方最优价
  price_type: 5

  # quick_trade: 下单时机
  #   - 0: K线走完下单（默认，当根K线结束时成交）
  #   - 1: 立即下单（收到信号立即下单）
  #   - 2: 强制立即下单
  quick_trade: 0
